INSERT INTO `genre` (`genre_name`) VALUES ('Alternative Rock');
INSERT INTO `genre` (`genre_name`) VALUES ('Reggae');
INSERT INTO `genre` (`genre_name`) VALUES ('Classical');
INSERT INTO `genre` (`genre_name`) VALUES ('R&B');
INSERT INTO `genre` (`genre_name`) VALUES ('Country');
INSERT INTO `genre` (`genre_name`) VALUES ('Jazz');
INSERT INTO `genre` (`genre_name`) VALUES ('Metal');
INSERT INTO `genre` (`genre_name`) VALUES ('Pop');
INSERT INTO `genre` (`genre_name`) VALUES ('New Age');
INSERT INTO `genre` (`genre_name`) VALUES ('Dance & Electronic');
INSERT INTO `genre` (`genre_name`) VALUES ('Rap & Hip-Hop');
INSERT INTO `genre` (`genre_name`) VALUES ('Latin Music');
INSERT INTO `genre` (`genre_name`) VALUES ('Rock');
INSERT INTO `genre` (`genre_name`) VALUES ('Gospel');
INSERT INTO `genre` (`genre_name`) VALUES ('Blues');
INSERT INTO `genre` (`genre_name`) VALUES ('Folk');
